export default {
    MAIN_PAGE               : 'Главная',
    INFORMATION             : 'Помощь',
    GALLERY                 : 'Темы',
    PHOTOBOOKS              : 'Фотокниги',
    DECORS                  : 'Интерьерная печать',
    SOUVENIRS               : 'Сувенирная продукция',
    POSTERS                 : 'Постеры',
    PHOTOS                  : 'Фотографии',
    CANVASES                : 'Холсты',
    CALENDARS               : 'Календари',
    PUZZLES                 : 'Пазлы',
    OTHERS                  : 'Прочее',
    NEW_PRODUCTS            : 'Новые',
    OPTIONS                 : 'Опции',
    POSTER_EDITOR           : 'Редактирование постера',
    SHOP                    : 'Магазин',
    MY_SHOP                 : 'Мой магазин',
    GIFT_CARD               : 'Подарочный сертификат',
    MY_PHOTO_BOOKS          : 'Мои фотокниги',
    MY_PRODUCTS             : 'Мои проекты',
    MY_PHOTOS               : 'Мои фотографии',
    PROFILE                 : 'Профиль',
    MENU                    : 'Меню',
    SITE_MAP                : 'Карта сайта',
    ADMIN_PANEL             : 'Администрирование',
    CONTACTS                : 'Контакты',
    INFO                    : 'Информация',
    ABOUT_COMPANY           : 'О нас',
    BLOG                    : 'Блог',
    SALES                   : 'Акции',
    EDITOR                  : 'Редактор',
    SUBSCRIPTION            : 'Подписка на рассылку',
    SOCIAL                  : 'Мы в соцсетях',
    COMPANY_NAME            : 'ООО «Ю ФО Ю»',
    PHONE_NUMBER            : '8 (495) 258 86 46',
    PHONE_NUMBER2           : '8 (925) 516-98-99',
    ADDRESS_TEXT            : 'Москва, ул. Красная Пресня, 28с2, офис 211',
    EMAIL_TEXT              : 'support@u4u.ru',
    ONLINE_EDITOR           : 'Онлайн редактор',
    PRODUCTS                : 'Продукты',
    THEMES                  : 'Темы',
    STICKERS                : 'Стикеры',
    BACKGROUNDS             : 'Фоны',
    FRAMES                  : 'Рамки',
    FONTS                   : 'Шрифты',
    STYLES                  : 'Стили',
    NOTIFICATIONS           : 'SMS и E-mail уведомления',
    DELIVERY                : 'Доставка',
    PRICE                   : 'Цена',
    PRICES                  : 'Стоимость',
    REQUISITES              : 'Реквизиты',
    HELP                    : 'Помощь',
    CART                    : 'Корзина',
    CART_COUNT              : 'Товаров в корзине',
    PUBLIC_OFFER            : 'Публичная оферта',
    CREATE                  : 'Создать',
    CONTINUE                : 'Продолжить',
    LOGIN                   : 'Войти',
    REGISTER                : 'Регистрация',
    TO_LOGIN                : 'Войти',
    TO_REGISTER             : 'Зарегистрироваться',
    TO_RESTORE              : 'Восстановить',
    SELECT                  : 'Выбрать',
    SELECT_THEME            : 'Смотреть темы',
    RESELECT_THEME          : 'Сменить тему',
    SEND_PWD_EMAIL          : 'Мы выслали вам пароль на электронную почту',
    SEND_PWD_PHONE          : 'Мы выслали вам SMS сообщение с паролем на телефон',
    SEND_PWD                : 'Выслать новый пароль',
    PHONE_OR_EMAIL_LABEL    : 'Мобильный телефон или e-mail',
    PASSWORD_LABEL          : 'Пароль',
    ERROR_LOGIN             : 'Введите мобильный телефон или e-mail',
    ERROR_PWD               : 'Введите пароль',
    SHOW_PWD                : 'Показать пароль',
    HIDE_PWD                : 'Скрыть пароль',
    OR_LOGIN_SOCIAL         : 'Или войдите через соцсети',
    ERROR_AUTH              : 'Не верный телефон/email или пароль',
    ERROR_EMAIL_NOT_EXIST   : 'Не верный e-mail',
    ERROR_PHONE_NOT_EXIST   : 'Не верный номер телефона',
    ERROR_NO_USER_FOUND     : 'Пользователь не найден',
    NOT_REGISTERED_YET      : 'Еще не зарегистрированы?',
    ALLREADY_REGISTERED     : 'Уже зарегистрированны?',
    ALLREADY_REMEMBER       : 'Вспомнили пароль?',
    FORGET_PASSWORD         : 'Забыли пароль?',
    RESTORE_PASSWORD        : 'Восстановление пароля',
    SUCCESS                 : 'Успешно',
    REMEMBER_PASSWORD       : 'Запомнить пароль',
    AUTH_AGREE_1            : 'Регистрируясь, вы подтверждаете согласие',
    AUTH_AGREE_2            : 'на обработку персональных данных',
    BACK                    : 'Назад',
    FORMAT                  : 'Формат',
    FORMATS                 : 'Форматы',
    COVER                   : 'Обложка',
    THE_COPY                : 'копия', // с маленькой буквы! добавка к имени при копировании продукта
    PHOTOBOOK_HARD_GLUE     : 'Фотокнига книжный переплет в твёрдой обложке',
    PHOTOBOOK_SOFT_GLUE     : 'Фотокнига книжный переплет в мягкой обложке',
    PHOTOBOOK_SOFT_CLIP     : 'Фотокнига на скрепке',
    PHOTOBOOK_HARD_SPRING   : 'Фотокнига на пружине в твёрдой обложке',
    PHOTOBOOK_SOFT_SPRING   : 'Фотокнига на пружине в мягкой обложке',
    JIVO_CHAT               : 'Задайте вопрос в чате',
    CALCULATE_PRICE         : 'Расчитать стоимость',
    CALCULATOR              : 'Калькулятор',
    VK                      : 'ВКонтакте',
    INSTAGRAM               : 'Instagram',
    GOOGLE                  : 'Google',
    // Величины и общие фразы
    VALUE_SM                : 'см.',
    VALUE_RUB               : 'руб.',
    VALUE_PAGE              : 'стр.',
    VALUE_GR_M              : 'гр/м',
    QUANTITY                : 'Кол-во',
    YES                     : 'Да',
    NO                      : 'Нет',
    CANCEL                  : 'Отменить',
    CANCEL_CHANGES          : 'Отменить изменения',
    CLOSE                   : 'Закрыть',
    SAVE                    : 'Сохранить',
    PUBLISH                 : 'Опубликовать',
    UNPUBLISH               : 'Снять с публикации',
    APPLY                   : 'Применить',
    CHOOSE                  : 'Выбрать',
    READY                   : 'Готово!',
    UPLOAD                  : 'Загрузить',
    FROM                    : 'от',
    TO                      : 'до',
    COPY                    : 'Копировать',
    PASTE                   : 'Вставить',
};
