export default {

    MY_PHOTOS_ALL               : 'Все фотографии',
    MY_PHOTOS_FOLDERS           : 'Папки',

    PHOTOS_UPLOAD               : 'Загрузка фотографий',
    U_CAN_DRAG_N_DROP           : 'Вы можете просто перетащить сюда фотографии или папку',
    UPLOAD_INFO                 : 'Требования к загружаемым файлам',
    OR_SOC_UPLOAD               : 'Или загрузить фото из соцсетей',
    SHOW_MORE                   : 'Показать еще',
    LOADING_MORE_PHOTOS         : 'Загружаю еще фотографии...',
    NO_PHOTOS                   : 'Нет фотографий',
    UPLOAD_PHOTOS               : 'Загрузить фотографии',
    UPLOAD_FROM_PC              : 'Загрузить с компьютера',
    UPLOAD_FROM_DEVICE          : 'Загрузить с устройства',
    ADD_PHOTOS                  : 'Добавить фотографии',
    UPLOAD_PHOTOS_MOB           : 'Загрузить',
    ADD_PHOTOS_MOB              : 'Добавить',
    IMPORT_PHOTOS               : 'Импорт фотографий из других сервисов',
    GOOGLE_PHOTOS               : 'Google photos',
    VK                          : 'ВКонтакте',
    YANDEX_PHOTO                : 'Яндекс фото',
    INSTAGRAM                   : 'Instagram',
    NEW_FOLDER                  : 'Создать папку',
    CHOOSE                      : 'Выбрать',
    CHOOSE_ALL                  : 'Выбрать все показанные',
    DESELECT                    : 'Снять выбор',
    DELETE                      : 'Удалить',
    DELETE_FOLDER               : 'Удалить папку',
    RENAME_FOLDER               : 'Переименовать папку',
    DUPLICATE                   : 'Скопировать',
    DUPLICATE_TO_FOLDER         : 'Скопировать в папку',
    ADD_TO_FOLDER               : 'Добавить в папку',
    MOVE_TO                     : 'Переместить',
    MOVE_IN                     : 'Перейти',
    MOVE_TO_SUCCESS             : 'Фотографии перемещены',
    DUPLICATE_SUCCESS           : 'Фотографии скопированы',
    DELETE_SUCCESS              : 'Фотографии удалены',
    DELETE_SUCCESS_F            : 'Фотографии удалены из папки',
    MOVE_TO_SUCCESS_1           : 'Фотография перемещена',
    DUPLICATE_SUCCESS_1         : 'Фотография скопирована',
    DELETE_SUCCESS_1            : 'Фотография удалена',
    DELETE_SUCCESS_F_1          : 'Фотография удалена из папки',
    DELETE_FOLDER_SUCCESS       : 'Папка удалена',
    DELETE_FOLDER_ERROR         : 'Ошибка при удалении папки',
    MOVE_TO_ERROR               : 'Ошибка при перемещении фотографий',
    DUPLICATE_ERROR             : 'Ошибка при копировании фотографий',
    DELETE_ERROR                : 'Ошибка при удалении фотографий',
    WS_ROTATE_ERROR             : 'Не удалось повернуть фотографию. Попробуйте еще раз',
    WS_UPLOAD_ERROR             : 'Не удалось загрузить фотографию. Попробуйте еще раз',
    DELETE_CONFIRM_QUESTION     : 'Вы уверены, что хотите удалить фотографии?',
    DELETE_CONFIRM_QUESTION_1   : 'Вы уверены, что хотите удалить фотографию?',
    DELETE_CONFIRM_QUESTION_F   : 'Вы уверены, что хотите удалить фотографии из папки?',
    DELETE_CONFIRM_QUESTION_F_1 : 'Вы уверены, что хотите удалить фотографию из папки?',
    DELETE_F_CONFIRM_QUESTION   : 'Вы уверены, что хотите удалить папку?',

    UPLOAD_LOAD                 : 'загрузка',
    UPLOAD_ERROR                : 'ошибка',

    SAVE                        : 'Сохранить',

    UPLOAD_TO_FOLDER_HELPHOVER  : 'Загруженные фотографии сохраняются в разделе "Все фотографии". Выберите этот пункт, если хотите скопировать загруженные фотографии в отдельную папку',

};
