export default {

    ERROR_REQUIRE_FILL_FIELD    : 'Это поле обязательно для заполнения',
    ERROR_PHONE                 : 'Не верно введен номер телефона',
    ERROR_EMAIL                 : 'Не верно введен e-mail',

    NOT_COMPLETED               : 'Новые',
    IN_ORDER                    : 'Заказы',
    DELETED                     : 'Удалено',
    CART                        : 'Корзина',
    ORDER                       : 'Заказ',
    ORDERED                     : 'Заказан',
    ORDER_SUM                   : 'Сумма заказа',
    MAKE_ORDER_BTN              : 'Оформить заказ',
    MAKE_ORDER                  : 'Заказать',
    MAKE_REORDER                : 'Заказать повторно',
    REMOVE_FROM_ORDER           : 'Убрать из заказа',
    VIEW                        : 'Просмотр',
    EDIT                        : 'Редактировать',
    MAKE_COPY                   : 'Создать копию',
    DELETE                      : 'Удалить',
    RECOVER                     : 'Восстановить',
    VIEW_ALBUM                  : 'Посмотреть альбом',
    VIEW_POSTER                 : 'Посмотреть постер',
    VIEW_PHOTO                  : 'Посмотреть фото',
    VIEW_CANVAS                 : 'Посмотреть холст',
    VIEW_CALENDAR               : 'Посмотреть календарь',
    CHANGE_NAME                 : 'Изменить название',
    ALBUM_NAME                  : 'Название альбома',
    ALBUM                       : 'Альбом',
    PHOTO                       : 'Фото',
    PHOTO_P                     : 'Фото премиум',
    POSTER_NAME                 : 'Название постера',
    POSTER                      : 'Постер',
    POSTER_P                    : 'Постер премиум',
    CANVAS                      : 'Холст',
    CALENDAR                    : 'Календарь',
    CALENDAR_WALL_SIMPLE        : 'Календарь одностраничный',
    CALENDAR_WALL_FLIP          : 'Календарь настенный',
    CALENDAR_TABLE_FLIP         : 'Календарь настольный',
    DECOR                       : 'Декор',
    PUZZLE                      : 'Пазл',
    ENTER_ALBUM_NAME            : 'Введите название альбома...',
    NOT_COMPLETED_EMPTY         : 'Нет новых продуктов.',
    IN_ORDER_EMPTY              : 'Заказов нет.',
    DELETED_EMPTY               : 'Нет удаленных продуктов.',
    CART_EMPTY                  : 'В корзине пусто.',
    MAKE_ORDER_ERROR            : 'Не удалось заказать альбом. Попробуйте повторить в редакторе.',
    MAKE_ORDER_ERROR_BTN        : 'Редактировать',
    MAKE_ORDER_SUCCESS          : 'Альбом успешно добавлен в корзину.',
    MAKE_ORDER_SUCCESS_LINK     : 'Перейти в корзину',
    NOT_COMPLETED_ERROR         : 'Не удалось загрузить новые продукты. Попробуйте позже.',
    IN_ORDER_ERROR              : 'Не удалось загрузить заказы. Попробуйте позже.',
    DELETED_ERROR               : 'Не удалось загрузить удаленные продукты. Попробуйте позже.',
    CART_ERROR                  : 'Не удалось загрузить корзину. Попробуйте позже.',
    COUNT                       : 'Тираж',
    STATUS                      : 'Статус',
    PROMOCODE                   : 'Промокод',
    PROMOCODE_DESC              : 'при наличии',
    IS_ACTIVE                   : 'активен!',
    COUPON                      : 'Купон',
    RESERVED_KEY                : 'Код бронирования (3 цифры)',
    PIN_CODE                    : 'Пин-код (4 цифры)',
    MY_DELIVERY                 : 'Оформление заказа',
    DELIVERY_TYPE               : 'Способ доставки',
    PICKUP                      : 'Самовывоз из офиса U4U',
    // PICKUP_TIME                 : '1-2 дня',
    DDELIVERY                   : 'Доставка по России',
    U4UDELIVERY                 : 'Доставка курьером U4U',
    // DELIVERY                    : 'Доставка',
    DELIVERY_ADDRESS            : 'Адрес доставки',
    // DELIVERY_COMPANY            : 'Доставка компанией',
    CONTACT_INFO                : 'Контактная информация',
    NAME                        : 'Имя',
    SURNAME                     : 'Фамилия',
    FATHERNAME                  : 'Отчество',
    PHONE                       : 'Телефон',
    EMAIL                       : 'E-mail',
    COMMENTS                    : 'Комментарии к заказу',
    GO_TO_CART                  : 'В корзину',
    PAY                         : 'Оплатить',
    USER_CONDITION_TEXT         : 'Нажимая кнопку "Оплатить", вы соглашаетесь с условиями ',
    USER_CONDITION_LINK         : 'пользовательского соглашения',
    DELIVERY_OFFICE_TEXT        : 'Вы можете забрать ваш заказ по адресу:',
    DELIVERY_OFFICE_ADDRESS     : 'г. Москва, ул. Красная Пресня, 28с2, офис 211 (Пн-Пт, 10:00 - 19:00)',
    DELIVERY_OFFICE_SHOW_MAP    : 'Показать на карте',
    DELIVERY_OFFICE_DESC        : 'Приходите к нам после получения сообщения, что заказ готов к выдаче.',
    FREE_PRICE                  : 'Бесплатно',
    DELIVERY_INFO_BTN           : 'Подробнее',
    DELIVERY_INFO_PICKUP_TITLE  : 'Самовывоз из офиса U4U',
    DELIVERY_INFO_PICKUP_TEXT_1 : 'Как только вы получите оповещение о готовности заказа, вы можете забрать его из офиса U4U, по адресу:',
    DELIVERY_INFO_PICKUP_TEXT_2 : 'г. Москва, ул. Красная Пресня, дом 28 строение 2, офис 211.',
    DELIVERY_INFO_PICKUP_TEXT_3 : `С понедельника по пятницу, с 11<sup>00</sup> до 19<sup>00</sup>`,
    DELIVERY_INFO_PICKUP_TEXT_4 : 'Тел: +7 (495) 258 86 46',
    DELIVERY_INFO_PICKUP_TEXT_5 : 'Около 5 минут пешком от метро «Улица 1905 года» или «Краснопресненская». Вход со двора, со стороны дома 26. Подъезд с вывеской "Нотариус" и табличкой U4U у входа.',
    DELIVERY_U4U_DELIVERY :       'Доставка заказа курьером U4U',
    DELIVERY_INFO_ORDER_NUMBER  : 'Номер заказа',
    DELIVERY_INFO_DATE          : 'Ориентировочная дата доставки',
    DELIVERY_INFO_DATE_WARNING  : 'Внимание! Срок доставки может быть увеличен курьерской компанией',
    DELIVERY_INFO_DATE_POSHTA_WARNING: 'Внимание! Срок доставки может быть увеличен Почтой России',
    DELIVERY_INFO_COURIER_PHONE : 'Телефон курьерской компании: ',
    DELIVERY_INFO_POCHTA_PHONE  : 'Телефон Почты России:',
    DELIVERY_INFO_PVZ_TITLE     : 'Доставка до пункта самовывоза',
    DELIVERY_INFO_PVZ_ADDRESS   : 'Адрес пункта самовывоза',
    DELIVERY_INFO_PVZ_DATE      : 'Дата поступления заказа в пункт доставки',
    DELIVERY_INFO_PVZ_TEXT_LAST : 'Вы можете забрать ваш заказ, как только получите оповещение о поступлении на пункт самовывоза.',
    DELIVERY_INFO_COURIER_TITLE : 'Доставка курьером',
    DELIVERY_INFO_COURIER_T_N   : 'Доставка курьером компании',
    DELIVERY_INFO_COURIER_T_L   : 'Перед приездом курьер свяжется с вами.',
    DELIVERY_INFO_POCHTA_TITLE  : 'Доставка Почтой России',
    DELIVERY_INFO_POCHTA_NAME   : 'Ваш заказ будет доставлен Почтой России',
    DELIVERY_INFO_POCHTA_LAST   : 'Как только заказ будет передан в "Почта России", вы получите трек-номер и сможете отcлеживать посылку на сайте по ссылке ниже.',
    DELIVERY_INFO_POCHTA_LINK   : 'Перейти на сайт "Почта России"',
    DELIVERY_INFO_COMPANY       : 'Компания доставки',
    DELIVERY_INFO_CHECK_STATUS  : 'Проверить статус',
    DELIVERY_TRACK_NUMBER       : 'Трек-номер',
    DELIVERY_TRACK_COST         : 'Стоимость доставки',

    ORDER_STATUS_INWORK         : 'Заказ оплачен',
    ORDER_STATUS_COMPLETED      : 'Доставляется',
    ORDER_STATUS_U4U_READY      : 'Готов к выдаче в офисе U4U',
    ORDER_STATUS_DONE           : 'Заказ выдан',
    PRODUCT_STATUS_COMPLETED    : 'Готов к заказу',
    PRODUCT_STATUS_INORDER      : 'В заказе',
    PRODUCT_STATUS_OPEN         : 'Не закончен',
    PRODUCT_STATUS_IN_SHOP      : 'Выставлен на продажу',

};
