export default {
    FIO               : 'Фамилия, имя, отчество',
    // GENDER            : 'Пол',
    MALE              : 'Мужчина',
    FEMALE            : 'Женщина',
    LOAD_AVA          : 'Загрузить фото',
    CLEAR_AVA         : 'Удалить аватар',
    CHANGE_PWD        : 'Сменить пароль',
    LOGOUT            : 'Выйти из аккаунта',
    PHONE             : 'Номер моб. телефона',
    EMAIL             : 'e-mail',
    PWD_OLD           : 'Текущий пароль',
    PWD_NEW           : 'Новый пароль',
    PWD_NEW_RE        : 'Повторите новый пароль',

    TAB_PERSONAL      : 'Персональные данные',
    TAB_CHANGE_PWD    : 'Смена пароля',
    TAB_SOCIAL        : 'Социальные профили',
    SOCIAL_BIND       : 'Привязать',
    SOCIAL_UNBIND     : 'Выйти',
    SOCIAL_TEXT       : 'Привяжи свой аккаунт и заходите на наш сервис в один клик',
    SOCIAL_LOGIN_LABEL      : 'Вы вошли как ',

    ERROR_PWD_OLD_EMPTY     : 'Введите текущий пароль',
    ERROR_PWD_OLD_WRONG     : 'Вы ввели неверный пароль',
    ERROR_PWD_NEW_EMPTY     : 'Введите новый пароль',
    ERROR_PWD_NEW_WRONG     : 'Новый пароль должен состоять только из латинских букв и цифр, и быть не короче 6 символов',
    ERROR_PWD_NEW_WRONG_S   : 'Новый пароль совпадает с текущим',
    ERROR_PWD_RE_WRONG      : 'Пароли отличаются',
    CHANGE_PWD_SUCCESS      : 'Пароль успешно обновлен!',
    CHANGE_PWD_UNKNOWN_ERR  : 'Не удалось поменять пароль',

    CHANGE_AVA_SUCCESS      : 'Фотография профиля успешно обновлена!',
    CHANGE_PROFILE_SUCCESS  : 'Профиль успешно обновлен!',
    CHANGE_PROFILE_ERROR    : 'Не удалось изменить данные профиля',

};
